# -*- coding: utf-8 -*-
"""
Created on Fri Jun 21 10:18:08 2019

@author: ric
"""
from tkinter import *

class Membership():
    def __int__(self):
            self.members = {1 :{ "KEY" : "1 - 1",          
                "NO." :	1,
                "UNIT" : 	1,
                "NAME" :  "Gentles",
                "ADDRESS" :  "1 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},

          2 :{"KEY" : "2 - 1 ", 
                "NO." :	1,	
                "UNIT" : 	2,
                "NAME" :  "Romeo",
                "ADDRESS" :  "2 - 436 Kingscourt Dr.",
                "MARKET RENT" :  885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
        3:{"KEY" : "3 - 1 ",
                "NO." :	1,
                "UNIT " : 	3,
                "NAME" :  "Poirier",
                "ADDRESS" :  "3 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        4:{"KEY" : "4 - 1 ",
                "NO." :	1,
                "UNIT" : 	4,
                "NAME" :  "Johnson",
                "ADDRESS" :  "4 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        5:{"KEY" : "5 - 1 ",
                "NO." :	1,
                "UNIT" : 	5,
                "NAME" :  "Crystal Frey",
                "ADDRESS" :  "5 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        6:{"KEY" : "6 - 1 ",
                "NO." :	1,
                "UNIT" : 	6,
                "NAME" :  "McNaul",
                "ADDRESS" :  "6 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        7:{"KEY" : "7 - 1 ",
                "NO." :	1,
                "UNIT" : 	7,
                "NAME" :  "Benoit",
                "ADDRESS" :  "7 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        8:{"KEY" : "8 - 1 ",
                "NO." :	1,
                "UNIT" : 	8,
                "NAME" :  "Mahamed",
                "ADDRESS" :  "8 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        9:{"KEY" : "9 - 1 ",
                "NO." :	1,
                "UNIT" : 	9,
                "NAME" :  "Kocher",
                "ADDRESS" :  "9 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE" : "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        10:{"KEY" : "10 - 1 ",
                "NO." :	1,
                "UNIT" : 	10,
                "NAME" :  "Griffith	",
                "ADDRESS" :  "10 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        11:{"KEY" : "11 - 1 ",
                "NO." :	1,
                "UNIT" : 	11,
                "NAME" :  "Jozwiak",
                "ADDRESS" :  "11 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        12:{"KEY" : "12 - 1 ",
                "NO." :	1,
                "UNIT" : 	12,
                "NAME" :  "Swartz",
                "ADDRESS" :  "12 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00	, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        13:{"KEY" : "13 - 1 ",
                "NO." :	1,
                "UNIT" : 	13,
                "NAME" :  "Gebrehiwet",
                "ADDRESS" :  "13 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        14:{"KEY" : "14 - 1 ",
                "NO." :	1,
                "UNIT" : 	14,
                "NAME" :  "Elzein",
                "ADDRESS" :  "14 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        15:{"KEY" : "14 - 2 ",
                "NO." :	2,
                "UNIT" : 	14,
                "NAME" :  "Hussein",
                "ADDRESS" :  "14 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        16:{"KEY" : "14 - 3 ",
                "NO." :	3,
                "UNIT" : 	14,
                "NAME" :  "Ahmed",
                "ADDRESS" :  "14 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        17:{"KEY" : "15 - 1 ",
                "NO." : 1	,
                "UNIT" : 	15,
                "NAME" :  "Turcotte",
                "ADDRESS" :  "	15 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        18:{"KEY" : "16 - 1 ",
                "NO." :	1,
                "UNIT" : 	16,
                "NAME" :  "Najar",
                "ADDRESS" :  "16 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        19:{"KEY" : "16 - 2 ",
                "NO." :	2,
                "UNIT" : 	16,
                "NAME" :  "Aboukakr",
                "ADDRESS" :  "16 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        20:{"KEY" : "17 - 1 ",
                "NO." :	1,
                "UNIT " : 	17,
                "NAME" :  "Nieuwesteeg",
                "ADDRESS" :  "17 - 436 Kingscourt Dr.",
                "MARKET RENT" : 810.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Townhouse",
                "UTILITIES BENEFIT" : 77.00,
                "APPLY BENEFIT" : True},
                
        21:{"KEY" : "18 - 1 ",
                "NO." :	1,
                "UNIT" : 	18,
                "NAME" :  "Griffith	",
                "ADDRESS" :  "18 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        22:{"KEY" : "19 - 1 ",
                "NO." :	1,
                "UNIT" : 	19,
                "NAME" :  "March",
                "ADDRESS" :  "19 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        23:{"KEY" : "20 - 1 ",
                "NO." :	1,
                "UNIT" : 	20,
                "NAME" :  "Hawco",
                "ADDRESS" :  "20 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        25:{"KEY" : "21 - 1 ",
                "NO." :	1,
                "UNIT" : 	21,
                "NAME" :  "",
                "ADDRESS" :  "21 - 436 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : "",
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        25:{"KEY" : "22 - 1 ",
                "NO." :	1,
                "UNIT" : 	22,
                "NAME" :  "Ric Woods",
                "ADDRESS" :  "22 - 456 Kingscourt Dr.",
                "MARKET RENT" : 810.00, 
                "CLASS" : "PRIMARY",
                "FAMILY SIZE" : 4,
                "INCOME SOURCE" : "Couples with/without beneficiaries",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Townhouse",
                "UTILITIES BENEFIT" : 77.00,
                "APPLY BENEFIT" : True},
                
        26:{"KEY" : "22 - 2 ",
                "NO." :	2,
                "UNIT" : 	22,
                "NAME" :  "john Woods",
                "ADDRESS" :  "22 - 456 Kingscourt Dr.",
                "MARKET RENT" : 810.00, 
                "CLASS" : "PRIMARY",
                "FAMILY SIZE" : 4,
                "INCOME SOURCE" : "Couples with/without beneficiaries",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Townhouse",
                "UTILITIES BENEFIT" : 77.00,
                "APPLY BENEFIT" : True},
                
        27:{"KEY" : "23 - 1",
                "NO." :	1,
                "UNIT" : 	23,
                "NAME" :  "Lasko",
                "ADDRESS" :  "23 - 456 Kingscourt Dr.",
                "MARKET RENT" : 940.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None ,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "4 Bed Townhouse",
                "UTILITIES BENEFIT" : 91.00,
                "APPLY BENEFIT" : True},
            
        28:{"KEY" : "24 - 1 ",
                "NO." :	1,
                "UNIT" : 	24,
                "NAME" :  "Brito",
                "ADDRESS" :  "24 - 456 Kingscourt Dr.",
                "MARKET RENT" : 940.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "4 Bed Townhouse",
                "UTILITIES BENEFIT" : 91.00,
                "APPLY BENEFIT" : True},
                
        29:{"KEY" : "25 - 1 ",
                "NO." :	1,
                "UNIT" : 	25,
                "NAME" :  "Akhtar",
                "ADDRESS" :  "25 - 456 Kingscourt Dr.",
                "MARKET RENT" : 940.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "4 Bed Townhouse",
                "UTILITIES BENEFIT" : 91.00,
                "APPLY BENEFIT" : True},
                
        30:{"KEY" : "26 - 1 ",
                "NO." :	1,
                "UNIT" : 	26,
                "NAME" :  "Buelvas",
                "ADDRESS" :  "26 - 456 Kingscourt Dr.",
                "MARKET RENT" : 940.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "Couples with/without beneficiaries",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "4 Bed Townhouse",
                "UTILITIES BENEFIT" : 91.00,
                "APPLY BENEFIT" : True},
                
        31:{"KEY" : "26 - 2 ",
                "NO." :	2,
                "UNIT" : 	26,
                "NAME" :  "Barrios",
                "ADDRESS" :  "26 - 456 Kingscourt Dr.",
                "MARKET RENT" : 940.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "4 Bed Townhouse",
                "UTILITIES BENEFIT" : 91.00,
                "APPLY BENEFIT" : True},
                
        32:{"KEY" : "27 - 1 ",
                "NO." :	27,
                "UNIT" : 	27,
                "NAME" :  "Kortleve",
                "ADDRESS" :  "27 - 456 Kingscourt Dr.",
                "MARKET RENT" : 810.00, 
                "CLASS" : "PRIMARY",
                "FAMILY SIZE" : 1,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Townhouse",
                "UTILITIES BENEFIT" : 77.00,
                "APPLY BENEFIT" : True},
                
        33:{"KEY" : "28 - 2 ",
                "NO." :	2,
                "UNIT" : 	28,
                "NAME" :  "",
                "ADDRESS" :  "28 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        34:{"KEY" : "29 - 1 ",
                "NO." :	1,
                "UNIT" :29,
                "NAME" :  "Arslan",
                "ADDRESS" :  "29 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : 1,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        35:{"KEY" : "30 - 1 ",
                "NO." :	1,
                "UNIT" : 	30,
                "NAME" :  "Hazara",
                "ADDRESS" :  "30 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        35:{"KEY" : "30 - 2 ",
                "NO." :	2,
                "UNIT" : 	30,
                "NAME" :  "Saeed",
                "ADDRESS" :  "30 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
                
        36:{"KEY" : "31 - 1 ",
                "NO." :	1,
                "UNIT" : 	31,
                "NAME" :  "Heer",
                "ADDRESS" :  "31 - 456 Kingscourt Dr.",
                "MARKET RENT" : 940.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "4 Bed Townhouse",
                "UTILITIES BENEFIT" : 91.00,
                "APPLY BENEFIT" : True},
                
        37:{"KEY" : "32 - 1 ",
                "NO." :	1,
                "UNIT" : 	32,
                "NAME" :  "Edwards",
                "ADDRESS" :  "43 - 456 Kingscourt Dr.",
                "MARKET RENT" : 940.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "4 Bed Townhouse",
                "UTILITIES BENEFIT" : 91.00,
                "APPLY BENEFIT" : True},
            
        38:{"KEY" : "33 - 1 ",
                "NO." :	1,
                "UNIT" : 	33,
                "NAME" :  "Koch",
                "ADDRESS" :  "33 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        39:{"KEY" : "34 - 1 ",
                "NO." :	1,
                "UNIT" : 	34,
                "NAME" :  "Walsh",
                "ADDRESS" :  "34 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        40:{"KEY" : "35 - 1 ",
                "NO." :	1,
                "UNIT" : 	35,
                "NAME" :  "Peacock",
                "ADDRESS" :  "35 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        41:{"KEY" : "36 - 1 ",
                "NO." :	1,
                "UNIT" : 	36,
                "NAME" :  "Foote",
                "ADDRESS" :  "36 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        42:{"KEY" : "37 - 1 ",
                "NO." :	1,
                "UNIT" : 	37,
                "NAME" :  "Lepetre",
                "ADDRESS" :  "30 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        43:{"KEY" : "38 - 1 ",
                "NO." :	1,
                "UNIT" : 	38,
                "NAME" :  "Bowman",
                "ADDRESS" :  "38 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        44:{"KEY" : "38 - 2 ",
                "NO." :	2,
                "UNIT" : 	38,
                "NAME" :  "Langridge",
                "ADDRESS" :  "30 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        45:{"KEY" : "39 - 1 ",
                "NO." :	1,
                "UNIT" : 	39,
                "NAME" :  "Qamar",
                "ADDRESS" :  "39 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        46:{"KEY" : "40 - 1 ",
                "NO." :	1,
                "UNIT" : 	40,
                "NAME" :  "O'Neil",
                "ADDRESS" :  "40 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        47:{"KEY" : "40 - 2 ",
                "NO." :	2,
                "UNIT" : 	40,
                "NAME" :  "Chapman",
                "ADDRESS" :  "40 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        48:{"KEY" : "41 - 1 ",
                "NO." :	1,
                "UNIT" : 	41,
                "NAME" :  "Daudlin",
                "ADDRESS" :  "41 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        49:{"KEY" : "42 - 1 ",
                "NO." :	1,
                "UNIT" : 	42,
                "NAME" :  "Munene",
                "ADDRESS" :  "42 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        50:{"KEY" : "43 - 1 ",
                "NO." :	1,
                "UNIT" : 	43,
                "NAME" :  "Boumar",
                "ADDRESS" :  "43 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        51:{"KEY" : "43 - 2 ",
                "NO." :	2,
                "UNIT" : 	43,
                "NAME" :  "Al-Timanl",
                "ADDRESS" :  "43 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        52:{"KEY" : "44 - 1 ",
                "NO." :	1,
                "UNIT" : 	44,
                "NAME" :  "Asif",
                "ADDRESS" :  "44 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        53:{"KEY" : "45 - 1 ",
                "NO." :	1,
                "UNIT" : 	45,
                "NAME" :  "Wheeler",
                "ADDRESS" :  "45 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        54:{"KEY" : "46 - 1 ",
                "NO." :	1,
                "UNIT" : 	46,
                "NAME" :  "England",
                "ADDRESS" :  "47 - 456 Kingscourt Dr.",
                "MARKET RENT" : 885.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "3 Bed Townhouse",
                "UTILITIES BENEFIT" : 84.00,
                "APPLY BENEFIT" : True},
            
        55:{"KEY" : "101 - 1 ",
                "NO." :	1,
                "UNIT" : 	101,
                "NAME" :  "Mekuria",
                "ADDRESS" :  "101 - 446 Kingscourt Dr.",
                "MARKET RENT" : 630.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "1 Bed Apartment",
                "UTILITIES BENEFIT" : 45.00,
                "APPLY BENEFIT" : True},
            
        56:{"KEY" : "102 - 1 ",
                "NO." :	1,
                "UNIT" : 	102,
                "NAME" :  "ILC",
                "ADDRESS" :  "102 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
            
        57:{"KEY" : "103 - 1 ",
                "NO." :	1,
                "UNIT" : 	103,
                "NAME" :  "Unsworth",
                "ADDRESS" :  "103 - 446 Kingscourt Dr.",
                "MARKET RENT" : 630.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "1 Bed Apartment",
                "UTILITIES BENEFIT" : 45.00,
                "APPLY BENEFIT" : True},
            
        58:{"KEY" : "104 - 1 ",
                "NO." :	1,
                "UNIT" : 	162,
                "NAME" :  "McClellan",
                "ADDRESS" :  "104 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
            
        59:{"KEY" : "105 - 1 ",
                "NO." :	1,
                "UNIT" : 	105,
                "NAME" :  "Sampson",
                "ADDRESS" :  "102 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
            
        60:{"KEY" : "106 - 1 ",
                "NO." :	1,
                "UNIT" : 	106,
                "NAME" :  "Kellum",
                "ADDRESS" :  "106 - 446 Kingscourt Dr.",
                "MARKET RENT" : 630.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "1 Bed Apartment",
                "UTILITIES BENEFIT" : 45.00,
                "APPLY BENEFIT" : True},
            
        60:{"KEY" : "107 - 1 ",
                "NO." :	1,
                "UNIT" : 	107,
                "NAME" :  "Boshart",
                "ADDRESS" :  "107 - 446 Kingscourt Dr.",
                "MARKET RENT" : 630.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "1 Bed Apartment",
                "UTILITIES BENEFIT" : 45.00,
                "APPLY BENEFIT" : True},
            
        61:{"KEY" : "109 - 1 ",
                "NO." :	1,
                "UNIT" : 	108,
                "NAME" :  "Craigie",
                "ADDRESS" :  "108 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
            
        62:{"KEY" : "109 - 1 ",
                "NO." :	1,
                "UNIT" : 	102,
                "NAME" :  "",
                "ADDRESS" :  "109 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,

                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
            
        63:{"KEY" : "110 - 1 ",
                "NO." :	1,
                "UNIT" : 	110,
                "NAME" :  "Larsen",
                "ADDRESS" :  "110 - 446 Kingscourt Dr.",
                "MARKET RENT" : 630.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "1 Bed Apartment",
                "UTILITIES BENEFIT" : 45.00,
                "APPLY BENEFIT" : True},
            
        64:{"KEY" : "111 - 1 ",
                "NO." :	1,
                "UNIT" : 	111,
                "NAME" :  "Doug Stone",
                "ADDRESS" :  "111 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
            
        65:{"KEY" : "112 - 1 ",
                "NO." :	1,
                "UNIT" : 	112,
                "NAME" :  "Trish Stone",
                "ADDRESS" :  "112 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
        65:{"KEY" : "201 - 1 ",
                "NO." :	1,
                "UNIT" : 	201,
                "NAME" :  "Wales",
                "ADDRESS" :  "201 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        66:{"KEY" : "202 - 1 ",
                "NO." :	1,
                "UNIT" : 	202,
                "NAME" :  "Frank",
                "ADDRESS" :  "202 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        67:{"KEY" : "203 - 1 ",
                "NO." :	1,
                "UNIT" : 	203,
                "NAME" :  "Deen",
                "ADDRESS" :  "203 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        68:{"KEY" : "204 - 1 ",
                "NO." :	1,
                "UNIT" : 	204,
                "NAME" :  "Jaxques",
                "ADDRESS" :  "204 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        60:{"KEY" : "205 - 1 ",
                "NO." :	1,
                "UNIT" : 	205,
                "NAME" :  "Mikel",
                "ADDRESS" :  "205 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        70:{"KEY" : "206 - 1 ",
                "NO." :	1,
                "UNIT" : 	206,
                "NAME" :  "Doerr",
                "ADDRESS" :  "206 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
        71:{"KEY" : "207 - 1 ",
                "NO." :	1,
                "UNIT" : 	207,
                "NAME" :  "",
                "ADDRESS" :  "209 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
            
        72:{"KEY" : "208 - 1 ",
                "NO." :	1,
                "UNIT" : 	208,
                "NAME" :  "Ryan",
                "ADDRESS" :  "208 - 446 Kingscourt Dr.",
                "MARKET RENT" : 630.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "1 Bed Apartment",
                "UTILITIES BENEFIT" : 45.00,
                "APPLY BENEFIT" : True},

        73:{"KEY" : "209 - 1 ",
                "NO." :	1,
                "UNIT" : 	209,
                "NAME" :  "Gaebel",
                "ADDRESS" :  "209 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        74:{"KEY" : "210 - 1 ",
                "NO." :	1,
                "UNIT" : 	210,
                "NAME" :  "Heise",
                "ADDRESS" :  "210 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        75:{"KEY" : "211 - 1 ",
                "NO." :	1,
                "UNIT" : 	211,
                "NAME" :  "Pulley",
                "ADDRESS" :  "211 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        76:{"KEY" : "212 - 1 ",
                "NO." :	1,
                "UNIT" : 	212,
                "NAME" :  "Cox",
                "ADDRESS" :  "212 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        77:{"KEY" : "213 - 1 ",
                "NO." :	1,
                "UNIT" : 	213,
                "NAME" :  "Griffith",
                "ADDRESS" :  "213- 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        78:{"KEY" : "214 - 1 ",
                "NO." :	1,
                "UNIT" : 	214,
                "NAME" :  "Meika",
                "ADDRESS" :  "112 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},
            
        79:{"KEY" : "215 - 1 ",
                "NO." :	1,
                "UNIT" : 	215,
                "NAME" :  "Miller",
                "ADDRESS" :  "215 - 446 Kingscourt Dr.",
                "MARKET RENT" : 630.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "1 Bed Apartment",
                "UTILITIES BENEFIT" : 45.00,
                "APPLY BENEFIT" : True},

        80:{"KEY" : "216 - 1 ",
                "NO." :	1,
                "UNIT" : 	216,
                "NAME" :  "McDermott",
                "ADDRESS" :  "112 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        81:{"KEY" : "301 - 1 ",
                "NO." :	1,
                "UNIT" : 	301,
                "NAME" :  "",
                "ADDRESS" :  "301 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        82:{"KEY" : "302 - 1 ",
                "NO." :	1,
                "UNIT" : 	302,
                "NAME" :  "Riedl",
                "ADDRESS" :  "302 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        83:{"KEY" : "303 - 1 ",
                "NO." :	1,
                "UNIT" : 	303,
                "NAME" :  "Rhindress",
                "ADDRESS" :  "303 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        84:{"KEY" : "304 - 1 ",
                "NO." :	1,
                "UNIT" : 	304,
                "NAME" :  "	Julie England",
                "ADDRESS" :  "304 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "PRIMARY",
                "FAMILY SIZE" : 1,
                "INCOME SOURCE" : "ODSP",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        85:{"KEY" : "305 - 1 ",
                "NO." :	1,
                "UNIT" : 	305,
                "NAME" :  "Coleen Griffith",
                "ADDRESS" :  "305 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        86:{"KEY" : "306 - 1 ",
                "NO." :	1,
                "UNIT" : 	306,
                "NAME" :  "Perry",
                "ADDRESS" :  "306 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        87:{"KEY" : "307 - 1 ",
                "NO." :	1,
                "UNIT" : 	307,
                "NAME" :  "",
                "ADDRESS" :  "307 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        88:{"KEY" : "308 - 1 ",
                "NO." :	1,
                "UNIT" : 	110,
                "NAME" :  "Wright",
                "ADDRESS" :  "308 - 446 Kingscourt Dr.",
                "MARKET RENT" : 630.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "1 Bed Apartment",
                "UTILITIES BENEFIT" : 45.00,
                "APPLY BENEFIT" : True},

        89:{"KEY" : "309 - 1 ",
                "NO." :	1,
                "UNIT" : 	309,
                "NAME" :  "Arlene Stone",
                "ADDRESS" :  "309 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        90:{"KEY" : "310 - 1 ",
                "NO." :	1,
                "UNIT" : 	310,
                "NAME" :  "Garrah",
                "ADDRESS" :  "310 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        91:{"KEY" : "311 - 1 ",
                "NO." :	1,
                "UNIT" : 	311,
                "NAME" :  "Cantley",
                "ADDRESS" :  "311 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        92:{"KEY" : "312 - 1 ",
                "NO." :	1,
                "UNIT" : 	312,
                "NAME" :  "Duke",
                "ADDRESS" :  "312 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        93:{"KEY" : "313 - 1 ",
                "NO." :	1,
                "UNIT" : 	313,
                "NAME" :  "",
                "ADDRESS" :  "313 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        94:{"KEY" : "314 - 1 ",
                "NO." :	1,
                "UNIT" : 	314,
                "NAME" :  "Marlon Griffin",
                "ADDRESS" :  "112 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True},

        95:{"KEY" : "315 - 1 ",
                "NO." :	1,
                "UNIT" : 	315,
                "NAME" :  "Ronnenberg",
                "ADDRESS" :  "315 - 446 Kingscourt Dr.",
                "MARKET RENT" : 630.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "1 Bed Apartment",
                "UTILITIES BENEFIT" : 45.00,
                "APPLY BENEFIT" : True},

        96:{"KEY" : "216 - 1 ",
                "NO." :	1,
                "UNIT" : 	315,
                "NAME" :  "",
                "ADDRESS" :  "316 - 446 Kingscourt Dr.",
                "MARKET RENT" : 695.00, 
                "CLASS" : "",
                "FAMILY SIZE" : None,
                "INCOME SOURCE" : "",
                "INCOME AMOUNT" : "",
                "EMP. EXEMPT" : False,
                "UNIT TYPE": "2 Bed Apartment",
                "UTILITIES BENEFIT" : 47.00,
                "APPLY BENEFIT" : True}
        }
            
    def DisplayMembers(self):
        pass
        
class RentScale():
    def __int__(self):
        self.ratescale = []
        self.ratescale.append({"FAMILY SIZE" : 1,"2OW-RENT" : "","2OW-LIMIT" :  "","3OW-RENT" : 85,"3OW-LIMIT" : 360,"4ODSP-RENT" : 109,"4ODSP-LIMIT" : 440})
        self.ratescale.append({"FAMILY SIZE" : 2,"2OW-RENT" : 191,"2OW-LIMIT" : 791,"3OW-RENT" : 175,"3OW-LIMIT" : 	737,"4ODSP-RENT" : 199,"4ODSP-LIMIT" : 817})
        self.ratescale.append({"FAMILY SIZE" : 3,"2OW-RENT" : 226,"2OW-LIMIT" : 907,"3OW-RENT" : 212,"3OW-LIMIT" : 	861,"4ODSP-RENT" : 236,"4ODSP-LIMIT" : 	941})
        self.ratescale.append({"FAMILY SIZE" : 4,"2OW-RENT" : 296,"2OW-LIMIT" : 1051,"3OW-RENT" : 254,"3OW-LIMIT" : 1001,"4ODSP-RENT" : 	279,"4ODSP-LIMIT" : 	1081})
        self.ratescale.append({"FAMILY SIZE" : 5,"2OW-RENT" : 311,"2OW-LIMIT" : 1191,"3OW-RENT" : 	296,"3OW-LIMIT" : 1141,"4ODSP-RENT" : 321	,"4ODSP-LIMIT" : 1224})
        self.ratescale.append({"FAMILY SIZE" : 6,"2OW-RENT" : 353,"2OW-LIMIT" : 1331,"3OW-RENT" : 	339,"3OW-LIMIT" : 1284,"4ODSP-RENT" : 363,"4ODSP-LIMIT" : 	1364})
        self.ratescale.append({"FAMILY SIZE" : 7,"2OW-RENT" : 396,"2OW-LIMIT" : 1474,"3OW-RENT" : 	381,"3OW-LIMIT" : 1424,"4ODSP-RENT" : 405,"4ODSP-LIMIT" : 1504})
        self.ratescale.append({"FAMILY SIZE" : 8,"2OW-RENT" : 438,"2OW-LIMIT" : 1614,"3OW-RENT" : 	423,"3OW-LIMIT" : 1564,"4ODSP-RENT" : 448	,"4ODSP-LIMIT" : 1647})
        self.ratescale.append({"FAMILY SIZE" : 9,"2OW-RENT" : 480,"2OW-LIMIT" : 1754,"3OW-RENT" : 	466,"3OW-LIMIT" : 1707,"4ODSP-RENT" : 490,"4ODSP-LIMIT" : 1787})
        self.ratescale.append({"FAMILY SIZE" : 10,"2OW-RENT" : 523,"2OW-LIMIT" : 1897,"3OW-RENT" : 508	,"3OW-LIMIT" : 1897,"4ODSP-RENT" : 532,"4ODSP-LIMIT" : 1847})
        self.ratescale.append({"FAMILY SIZE" : 11,"2OW-RENT" : 565,"2OW-LIMIT" : 2037,"3OW-RENT" : 550,"3OW-LIMIT" : 1847,"4ODSP-RENT" : 575,"4ODSP-LIMIT" : 1987})
        self.ratescale.append({"FAMILY SIZE" : 12,"2OW-RENT" : 607,"2OW-LIMIT" : 2177,"3OW-RENT" : 593,"3OW-LIMIT" : 2131,"4ODSP-RENT" : 617,"4ODSP-LIMIT" : 2211})

class SCInput():
    def __int__(self,base):
        self.base.title("Subsidy Calculor Input")
        
    def displaySCInput(self):
        pass
        
class SCOutput():
    def __int__(self,base):
        self.base.title("Subsidy Calculor Output")
        
    def displaySCOutput(self):
        pass
   
class SCPrint():
    def __int__(self,base):
        self.base.title("Subsidy Calculor Print")
        
    def displaySCPrint(self):
        pass
    
class Units():
    pass
      
class Code():
    def __int__(self,base):
        self.base.title("Cods")
        
    def displaySCCode(self):
        pass
    
class Overview():
    pass

class Input():
    pass

class Output():
    pass

class Codes():      
    pass

class menu():
    def __init__(self,base):
        self.base = base

    def displaymenu(self,base):
        self.menubar = Menu()
        self.SCInput = SCInput()
        self.menubar.add_command(label="!nput", command=self.SCInput.displaySCInput())
        self.SCOutput = SCOutput()
        self.menubar.add_command(label="Output", command=self.SCOutput.displaySCOutput())
        self.SCPrint = SCPrint()
        self.menubar.add_command(label="Print", command=self.SCPrint.displaySCPrint())
        self.settingmenu = Menu(self.menubar, tearoff=0)
        self.Membership = Membership()
        self.settingmenu.add_command(label="Members",ommand=self.Membership.DisplayMembers())
        self.settingmenu.add_command(label="Units", command=Units())
        self.settingmenu.add_command(label="RentScale", command= RentScale())
        self.menubar.add_cascade(label="Setting", menu=self.settingmenu)
        self.helpmenu = Menu(self.menubar, tearoff=0)
        self.helpmenu.add_command(label="Overview", command=Overview())
        self.helpmenu.add_command(label="Input", command=Input())
        self.helpmenu.add_command(label="Output", command=Output())
        self.helpmenu.add_command(label="Codes", command=Codes())
        self.menubar.add_cascade(label="Help", menu=self.helpmenu)
        self.menubar.add_command(label="Exit", command=base.quit)
        base.config(menu=self.menubar)

base = Tk()
base.title("Subsidy Calculor")
base.geometry(f"{base.winfo_screenwidth()}x{base.winfo_screenheight()}+0+0")
#menuframe = base.frame()
#base.menuframe.grid_location(0,0)
menu = menu(base)
menu.displaymenu(base)
#menuframe = base.frame()
#menuframe.grid_location(0,0)
#menu.displaymenu(base)
#SCInput = SCInput()
#SCInputframe = base.frame()
##SCInputframe.grid_location(1,0)
#SCInput.displaySCInput()
base.mainloop()

