"""
Created on Fri Nov  8 14:31:39 2019

@author: ric
"""


import pickle
KEY1_1 = {"NO.": 1,
          "UNIT": '1',
          "NAME": "Gentles",
          "ADDRESS":  "1-436 Kingscourt Dr.",
          "MARKET RENT": 885.00,
          "CLASS": "",
          "FAMILY SIZE": "",
          "INCOME SOURCE":  "",
          "INCOME AMOUNT":  "",
          "EMP. EXEMPT": False,
          "UNIT TYPE": "3 Bed Townhouse",
          "UTILITIES BENEFIT": 84.00,
          "APPLY BENEFIT": True}

KEY2_1 = {"NO.": 1,
          "UNIT": '2',
          "NAME":  "Romeo",
          "ADDRESS":  "2-436 Kingscourt Dr.",
          "MARKET RENT":  885.00,
          "CLASS": "",
          "FAMILY SIZE": "",
          "INCOME SOURCE": "",
          "INCOME AMOUNT": "",
          "EMP. EXEMPT": False,
          "UNIY TYPE": "3 Bed Townhouse",
          "UTILITIES BENEFIT": 84.00,
          "APPLY BENEFIT": True}

KEY3_1 = {"NO.": 1,
          "UNIT": '3',
          "NAME":  "Poirier",
          "ADDRESS":  "3-436 Kingscourt Dr.",
          "MARKET RENT": 885.00,
          "CLASS": "",
          "FAMILY SIZE": "",
          "INCOME SOURCE": "",
          "INCOME AMOUNT": "",
          "EMP. EXEMPT": False,
          "UNIT TYPE": "3 Bed Townhouse",
          "UTILITIES BENEFIT": 84.00,
          "APPLY BENEFIT": True}

KEY4_1 = {"NO.": 1,
          "UNIT": '4',
          "NAME":  "Johnson",
          "ADDRESS":  "4-436 Kingscourt Dr.",
          "MARKET RENT": 885.00,
          "CLASS": "",
          "FAMILY SIZE": "",
          "INCOME SOURCE": "",
          "INCOME AMOUNT": "",
          "EMP. EXEMPT": False,
          "UNIT TYPE": "3 Bed Townhouse",
          "UTILITIES BENEFIT": 84.00,
          "APPLY BENEFIT": True}

KEY5_1 = {"NO.": 1,
          "UNIT": '5',
          "NAME":  "Crystal Frey",
          "ADDRESS":  "5-436 Kingscourt Dr.",
          "MARKET RENT": 885.00,
          "CLASS": "",
          "FAMILY SIZE": "",
          "INCOME SOURCE": "",
          "INCOME AMOUNT": "",
          "EMP. EXEMPT": False,
          "UNIT TYPE": "3 Bed Townhouse",
          "UTILITIES BENEFIT": 84.00,
          "APPLY BENEFIT": True}
KEY6_1 = {"NO.": 1,
          "UNIT": '6',
          "NAME":  "McNaul",
          "ADDRESS":  "6-436 Kingscourt Dr.",
          "MARKET RENT": 885.00,
          "CLASS": "",
          "FAMILY SIZE": "",
          "INCOME SOURCE": "",
          "INCOME AMOUNT": "",
          "EMP. EXEMPT": False,
          "UNIT TYPE": "3 Bed Townhouse",
          "UTILITIES BENEFIT": 84.00,
          "APPLY BENEFIT": True}
KEY7_1 = {"NO.": 1,
          "UNIT": '7',
          "NAME":  "Benoit",
          "ADDRESS":  "7-436 Kingscourt Dr.",
          "MARKET RENT": 885.00,
          "CLASS": "",
          "FAMILY SIZE": "",
          "INCOME SOURCE": "",
          "INCOME AMOUNT": "",
          "EMP. EXEMPT": False,
          "UNIT TYPE": "3 Bed Townhouse",
          "UTILITIES BENEFIT": 84.00,
          "APPLY BENEFIT": True}

KEY8_1 = {"NO.": 1,
          "UNIT": '8',
          "NAME":  "Mahamed",
          "ADDRESS":  "8-436 Kingscourt Dr.",
          "MARKET RENT": 885.00,
          "CLASS": "",
          "FAMILY SIZE": "",
          "INCOME SOURCE": "",
          "INCOME AMOUNT": "",
          "EMP. EXEMPT": False,
          "UNIT TYPE": "3 Bed Townhouse",
          "UTILITIES BENEFIT": 84.00,
          "APPLY BENEFIT": True}

KEY9_1 = {"NO.": 1,
          "UNIT": '9',
          "NAME":  "Kocher",
          "ADDRESS":  "9-436 Kingscourt Dr.",
          "MARKET RENT": 885.00,
          "CLASS": "",
          "FAMILY SIZE": "",
          "INCOME SOURCE": "",
          "INCOME AMOUNT": "",
          "EMP. EXEMPT": False,
          "UNIT TYPE": "3 Bed Townhouse",
          "UTILITIES BENEFIT": 84.00,
          "APPLY BENEFIT": True}

KEY10_1 = {"NO.": 1,
           "UNIT": '10',
           "NAME":  "Griffith    ",
           "ADDRESS":  "10-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY11_1 = {"NO.": 1,
           "UNIT": '11',
           "NAME":  "Jozwiak",
           "ADDRESS":  "11-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY12_1 = {"NO": 1,
           "UNIT": '12',
           "NAME":  "Swartz",
           "ADDRESS":  "12-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY13_1 = {"NO": 1,
           "UNIT": '13',
           "NAME":  "Gebrehiwet",
           "ADDRESS":  "13-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY14_1 = {"NO": 1,
           "UNIT": '14',
           "NAME":  "Elzein",
           "ADDRESS":  "14-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY14_2 = {"NO.": 2,
           "UNIT": '14',
           "NAME":  "Hussein",
           "ADDRESS":  "14-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY14_3= {"NO.": 3,
           "UNIT": '14',
           "NAME":  "Ahmed",
           "ADDRESS":  "14-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY15_1 = {"NO": 1,
           "UNIT": '15',
           "NAME":  "Turcotte",
           "ADDRESS":  "    15-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY16_1 = {"NO": 1,
           "UNIT": '16',
           "NAME":  "Najar",
           "ADDRESS":  "16-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY16_2 = {"NO": 2,
           "UNIT": '16',
           "NAME":  "Aboukakr",
           "ADDRESS":  "16-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY17_1 = {"NO": 1,
           "UNIT": '17',
           "NAME":  "Nieuwesteeg",
           "ADDRESS":  "17-436 Kingscourt Dr.",
           "MARKET RENT": 810.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "2 Bed Townhouse",
           "UTILITIES BENEFIT": 77.00,
           "APPLY BENEFIT": True}

KEY18_1 = {"NO": 1,
           "UNIT": '18',
           "NAME":  "Griffith   ",
           "ADDRESS":  "18-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY19_1 = {"NO": 1,
           "UNIT": '19',
           "NAME":  "March",
           "ADDRESS":  "19-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY20_1 = {"NO": 1,
           "UNIT": '20',
           "NAME":  "Hawco",
           "ADDRESS":  "20-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY21_1 = {"NO": 1,
           "UNIT": '21',
           "NAME":  "",
           "ADDRESS":  "21-436 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": "",
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY22_1 = {"NO": 1,
           "UNIT": '22',
           "NAME":  "Ric Woods",
           "ADDRESS":  "22-456 Kingscourt Dr.",
           "MARKET RENT": 810.00,
           "CLASS": "PRIMARY",
           "FAMILY SIZE": 4,
           "INCOME SOURCE": "Couples with/without beneficiaries",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "2 Bed Townhouse",
           "UTILITIES BENEFIT": 77.00,
           "APPLY BENEFIT": True}

KEY22_2 = {"NO": 2,
           "UNIT": '22',
           "NAME":  "john Woods",
           "ADDRESS":  "22-456 Kingscourt Dr.",
           "MARKET RENT": 810.00,
           "CLASS": "PRIMARY",
           "FAMILY SIZE": 4,
           "INCOME SOURCE": "Couples with/without beneficiaries",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "2 Bed Townhouse",
           "UTILITIES BENEFIT": 77.00,
           "APPLY BENEFIT": True}

KEY23_1 = {"NO": 1,
           "UNIT": '23',
           "NAME":  "Lasko",
           "ADDRESS":  "23-456 Kingscourt Dr.",
           "MARKET RENT": 940.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "4 Bed Townhouse",
           "UTILITIES BENEFIT": 91.00,
           "APPLY BENEFIT": True}

KEY24_1 = {"NO": 1,
           "UNIT": '24',
           "NAME":  "Brito",
           "ADDRESS":  "24-456 Kingscourt Dr.",
           "MARKET RENT": 940.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "4 Bed Townhouse",
           "UTILITIES BENEFIT": 91.00,
           "APPLY BENEFIT": True}

KEY25_1 = {"NO": 1,
           "UNIT": '25',
           "NAME":  "Akhtar",
           "ADDRESS":  "25-456 Kingscourt Dr.",
           "MARKET RENT": 940.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "4 Bed Townhouse",
           "UTILITIES BENEFIT": 91.00,
           "APPLY BENEFIT": True}

KEY26_1 = {"NO": 1,
           "UNIT": '26',
           "NAME":  "Buelvas",
           "ADDRESS":  "26-456 Kingscourt Dr.",
           "MARKET RENT": 940.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "Couples with/without beneficiaries",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "4 Bed Townhouse",
           "UTILITIES BENEFIT": 91.00,
           "APPLY BENEFIT": True}

KEY26_2 = {"NO": 2,
           "UNIT": '26',
           "NAME":  "Barrios",
           "ADDRESS":  "26-456 Kingscourt Dr.",
           "MARKET RENT": 940.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "4 Bed Townhouse",
           "UTILITIES BENEFIT": 91.00,
           "APPLY BENEFIT": True}

KEY27_1 = {"NO": 1,
           "UNIT": '27',
           "NAME":  "Kortleve",
           "ADDRESS":  "27-456 Kingscourt Dr.",
           "MARKET RENT": 810.00,
           "CLASS": "PRIMARY",
           "FAMILY SIZE": 1,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "2 Bed Townhouse",
           "UTILITIES BENEFIT": 77.00,
           "APPLY BENEFIT": True}

KEY28_1 = {"NO": 1,
           "UNIT": '28',
           "NAME":  "",
           "ADDRESS":  "28-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY29_1 = {"NO": 1,
           "UNIT": '29',
           "NAME":  "Arslan",
           "ADDRESS":  "29-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": 1,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY30_1 = {"NO": 1,
           "UNIT": '30',
           "NAME":  "Hazara",
           "ADDRESS":  "30-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY31_1 = {"NO": 1,
           "UNIT": '31',
           "NAME":  "Heer",
           "ADDRESS":  "31-456 Kingscourt Dr.",
           "MARKET RENT": 940.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "4 Bed Townhouse",
           "UTILITIES BENEFIT": 91.00,
           "APPLY BENEFIT": True}

KEY32_1 = {"NO": 1,
           "UNIT": '32',
           "NAME":  "Edwards",
           "ADDRESS":  "43-456 Kingscourt Dr.",
           "MARKET RENT": 940.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "4 Bed Townhouse",
           "UTILITIES BENEFIT": 91.00,
           "APPLY BENEFIT": True}

KEY33_1 = {"NO": 1,
           "UNIT": '33',
           "NAME":  "Koch",
           "ADDRESS":  "33-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY34_1 = {"NO": 1,
           "UNIT": '34',
           "NAME":  "Walsh",
           "ADDRESS":  "34-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY35_1 = {"NO": 1,
           "UNIT": '35',
           "NAME":  "Peacock",
           "ADDRESS":  "35-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY36_1 = {"NO": 1,
           "UNIT": '36',
           "NAME":  "Foote",
           "ADDRESS":  "36-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY37_1 = {"NO": 1,
           "UNIT": '37',
           "NAME":  "Lepetre",
           "ADDRESS":  "30-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY38_1 = {"NO": 1,
           "UNIT": '38',
           "NAME":  "Bowman",
           "ADDRESS":  "38-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY38_2 = {"NO": 2,
           "UNIT": '38',
           "NAME":  "Langridge",
           "ADDRESS":  "30-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY39_1 = {"NO": 1,
           "UNIT": '39',
           "NAME":  "Qamar",
           "ADDRESS":  "39-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY40_1 = {"NO": 1,
           "UNIT": '40',
           "NAME":  "O'Neil",
           "ADDRESS":  "40-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY40_2 = {"NO": 2,
           "UNIT": '40',
           "NAME":  "Chapman",
           "ADDRESS":  "40-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY41_1 = {"NO": 1,
           "UNIT": '41',
           "NAME":  "Daudlin",
           "ADDRESS":  "41-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY42_1 = {"NO": 1,
           "UNIT": '42',
           "NAME":  "Munene",
           "ADDRESS":  "42-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY43_1 = {"NO": 1,
           "UNIT": '43',
           "NAME":  "Boumar",
           "ADDRESS":  "43-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY43_2 = {"NO": 2,
           "UNIT": '43',
           "NAME":  "Al_Timanl",
           "ADDRESS":  "43-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY44_1 = {"NO": 1,
           "UNIT": '44',
           "NAME":  "Asif",
           "ADDRESS":  "44-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY45_1 = {"NO": 1,
           "UNIT": '45',
           "NAME":  "Wheeler",
           "ADDRESS":  "45-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY46_1 = {"NO": 1,
           "UNIT": '46',
           "NAME":  "England",
           "ADDRESS":  "47-456 Kingscourt Dr.",
           "MARKET RENT": 885.00,
           "CLASS": "",
           "FAMILY SIZE": None,
           "INCOME SOURCE": "",
           "INCOME AMOUNT": "",
           "EMP. EXEMPT": False,
           "UNIT TYPE": "3 Bed Townhouse",
           "UTILITIES BENEFIT": 84.00,
           "APPLY BENEFIT": True}

KEY101_1 = {"NO": 1,
            "UNIT": '101',
            "NAME":  "Mekuria",
            "ADDRESS":  "101-446 Kingscourt Dr.",
            "MARKET RENT": 630.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "1 Bed Apartment",
            "UTILITIES BENEFIT": 45.00,
            "APPLY BENEFIT": True}

KEY102_1 = {"NO": 1,
            "UNIT": '102',
            "NAME":  "ILC",
            "ADDRESS":  "102-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY103_1 = {"NO": 1,
            "UNIT": '103',
            "NAME":  "Unsworth",
            "ADDRESS":  "103-446 Kingscourt Dr.",
            "MARKET RENT": 630.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "1 Bed Apartment",
            "UTILITIES BENEFIT": 45.00,
            "APPLY BENEFIT": True}

KEY104_1 = {"NO": 1,
            "UNIT": '104',
            "NAME":  "McClellan",
            "ADDRESS":  "104-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY105_1 = {"NO": 1,
            "UNIT": '105',
            "NAME":  "Sampson",
            "ADDRESS":  "102-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY106_1 = {"NO": 1,
            "UNIT": '106',
            "NAME":  "Kellum",
            "ADDRESS":  "106-446 Kingscourt Dr.",
            "MARKET RENT": 630.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "1 Bed Apartment",
            "UTILITIES BENEFIT": 45.00,
            "APPLY BENEFIT": True}

KEY107_1 = {"NO": 1,
            "UNIT": '107',
            "NAME":  "Boshart",
            "ADDRESS":  "107-446 Kingscourt Dr.",
            "MARKET RENT": 630.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "1 Bed Apartment",
            "UTILITIES BENEFIT": 45.00,
            "APPLY BENEFIT": True}
KEY108_1 = {"NO": 1,
            "UNIT": '1O8',
            "NAME":  "Doris Craige",
            "ADDRESS":  "108-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY108_2 = {"NO": 2,
            "UNIT": '108',
            "NAME":  "Josh Craige",
            "ADDRESS":  "108-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY109_1 = {"NO": 1,
            "UNIT": '109',
            "NAME":  "",
            "ADDRESS":  "109-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY110_1 = {"NO": 1,
            "UNIT": '110',
            "NAME":  "Larsen",
            "ADDRESS":  "110-446 Kingscourt Dr.",
            "MARKET RENT": 630.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "1 Bed Apartment",
            "UTILITIES BENEFIT": 45.00,
            "APPLY BENEFIT": True}

KEY111_1 = {"NO": 1,
            "UNIT": '111',
            "NAME":  "Doug Stone",
            "ADDRESS":  "111-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY112_1 = {"NO": 1,
            "UNIT": '112',
            "NAME":  "Trish Stone",
            "ADDRESS":  "112-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}
KEY201_1 = {"NO": 1,
            "UNIT": '201',
            "NAME":  "Wales",
            "ADDRESS":  "201-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY202_1 = {"NO": 1,
            "UNIT": '202',
            "NAME":  "Frank",
            "ADDRESS":  "202-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY203_1 = {"NO": 1,
            "UNIT": '203',
            "NAME":  "Deen",
            "ADDRESS":  "203-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY204_1 = {"NO": 1,
            "UNIT": '204',
            "NAME":  "Jaxques",
            "ADDRESS":  "204-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY205_1 = {"NO": 1,
            "UNIT": '205',
            "NAME":  "Mikel",
            "ADDRESS":  "205-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY206_1 = {"NO": 1,
            "UNIT": '206',
            "NAME":  "Doerr",
            "ADDRESS":  "206-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}
KEY207_1 = {"NO": 1,
            "UNIT": '209',
            "NAME":  "",
            "ADDRESS":  "209-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY208_1 = {"NO": 1,
            "UNIT": '208',
            "NAME":  "Ryan",
            "ADDRESS":  "208-446 Kingscourt Dr.",
            "MARKET RENT": 630.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "1 Bed Apartment",
            "UTILITIES BENEFIT": 45.00,
            "APPLY BENEFIT": True}

KEY209_1 = {"NO": 1,
            "UNIT": '209',
            "NAME":  "Gaebel",
            "ADDRESS":  "209-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY210_1 = {"NO": 1,
            "UNIT": '210',
            "NAME":  "Heise",
            "ADDRESS":  "210-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY211_1 = {"NO": 1,
            "UNIT": '211',
            "NAME":  "Pulley",
            "ADDRESS":  "211-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY212_1 = {"NO": 1,
            "UNIT": '212',
            "NAME":  "Cox",
            "ADDRESS":  "212-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY213_1 = {"NO": 1,
            "UNIT": '213',
            "NAME":  "Griffith",
            "ADDRESS":  "213_ 446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}
KEY214_1 = {"NO": 1,
            "UNIT": '214',
            "NAME":  "Meika",
            "ADDRESS":  "112-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY215_1 = {"NO": 1,
            "UNIT": '215',
            "NAME":  "Miller",
            "ADDRESS":  "215-446 Kingscourt Dr.",
            "MARKET RENT": 630.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "1 Bed Apartment",
            "UTILITIES BENEFIT": 45.00,
            "APPLY BENEFIT": True}

KEY216_1 = {"NO": 1,
            "UNIT": '216',
            "NAME":  "McDermott",
            "ADDRESS":  "112-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY301_1 = {"NO": 1,
            "UNIT": '301',
            "NAME":  "",
            "ADDRESS":  "301-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}
KEY302_1 = {"NO": 1,
            "UNIT": '302',
            "NAME":  "Riedl",
            "ADDRESS":  "302-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY303_1 = {"NO": 1,
            "UNIT": '303',
            "NAME":  "Rhindress",
            "ADDRESS":  "303-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY304_1 = {"NO": 1,
            "UNIT": '304',
            "NAME":  "    Julie England",
            "ADDRESS":  "304-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "PRIMARY",
            "FAMILY SIZE": 1,
            "INCOME SOURCE": "ODSP",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY305_1 = {"NO": 1,
            "UNIT": '305',
            "NAME":  "Coleen Griffith",
            "ADDRESS":  "305-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY306_1 = {"NO": 1,
            "UNIT": '306',
            "NAME":  "Perry",
            "ADDRESS":  "306-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY307_1 = {"NO": 1,
            "UNIT": '307',
            "NAME":  "",
            "ADDRESS":  "307-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY308_1 = {"NO": 1,
            "UNIT": '308',
            "NAME":  "Wright",
            "ADDRESS":  "308-446 Kingscourt Dr.",
            "MARKET RENT": 630.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "1 Bed Apartment",
            "UTILITIES BENEFIT": 45.00,
            "APPLY BENEFIT": True}

KEY309_1 = {"NO": 1,
            "UNIT": '309',
            "NAME":  "Arlene Stone",
            "ADDRESS":  "309-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY310_1 = {"NO": 1,
            "UNIT": '310',
            "NAME":  "Garrah",
            "ADDRESS":  "310-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY311_1 = {"NO": 1,
            "UNIT": '311',
            "NAME":  "Cantley",
            "ADDRESS":  "311-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY312_1 = {"NO": 1,
            "UNIT": '312',
            "NAME":  "Duke",
            "ADDRESS":  "312-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY313_1 = {"NO": 1,
            "UNIT": '313',
            "NAME":  "",
            "ADDRESS":  "313-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY314_1 = {"NO": 1,
            "UNIT": '314',
            "NAME":  "Marlon Griffin",
            "ADDRESS":  "112-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

KEY315_1 = {"NO": 1,
            "UNIT" :'315',
            "NAME":  "Ronnenberg",
            "ADDRESS":  "315-446 Kingscourt Dr.",
            "MARKET RENT": 630.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "1 Bed Apartment",
            "UTILITIES BENEFIT": 45.00,
            "APPLY BENEFIT": True}

KEY316_1 = {"NO": 1,
            "UNIT": '315',
            "NAME":  "",
            "ADDRESS":  "316-446 Kingscourt Dr.",
            "MARKET RENT": 695.00,
            "CLASS": "",
            "FAMILY SIZE": None,
            "INCOME SOURCE": "",
            "INCOME AMOUNT": "",
            "EMP. EXEMPT": False,
            "UNIT TYPE": "2 Bed Apartment",
            "UTILITIES BENEFIT": 47.00,
            "APPLY BENEFIT": True}

members = {
   "KEY1_1": KEY1_1,
   "KEY2_1": KEY2_1,
   "KEY3_1": KEY3_1,
   "KEY4_1": KEY4_1,
   "KEY5_1": KEY5_1,
   "KEY6_1": KEY6_1,
   "KEY7_1": KEY7_1,
   "KEY8_1": KEY8_1,
   "KEY9_1": KEY9_1,
   "KEY10_1": KEY10_1,
   "KEY11_1": KEY11_1,
   "KEY12_1": KEY12_1,
   "KEY13_1": KEY13_1,
   "KEY14_1": KEY14_1,
   "KEY14_2": KEY14_2,
   "KEY14_3": KEY14_3,
   "KEY15_1": KEY15_1,
   "KEY16_1": KEY16_1,
   "KEY16_2": KEY16_2,
   "KEY17_1": KEY17_1,
   "KEY18_1": KEY18_1,
   "KEY19_1": KEY19_1,
   "KEY20_1": KEY20_1,
   "KEY21_1": KEY21_1,
   "KEY22_1": KEY22_1,
   "KEY23_1": KEY23_1,
   "KEY24_1": KEY24_1,
   "KEY25_1": KEY25_1,
   "KEY26_1": KEY26_1,
   "KEY27_1": KEY27_1,
   "KEY28_1": KEY28_1,
   "KEY29_1": KEY29_1,
   "KEY30_1": KEY30_1,
   "KEY31_1": KEY31_1,
   "KEY32_1": KEY32_1,
   "KEY33_1": KEY33_1,
   "KEY34_1": KEY34_1,
   "KEY35_1": KEY35_1,
   "KEY36_1": KEY36_1,
   "KEY37_1": KEY37_1,
   "KEY38_1": KEY38_1,
   "KEY38_2": KEY38_2,
   "KEY39_1": KEY39_1,
   "KEY40_1": KEY40_1,
   "KEY40_2": KEY40_2,
   "KEY41_1": KEY41_1,
   "KEY42_1": KEY42_1,
   "KEY43_2": KEY43_2,
   "KEY44_1": KEY44_1,
   "KEY45_1": KEY45_1,
   "KEY46_1": KEY46_1,
   "KEY101_1": KEY101_1,
   "KEY102_1": KEY102_1,
   "KEY103_1": KEY103_1,
   "KEY104_1": KEY104_1,
   "KEY105_1": KEY105_1,
   "KEY106_1": KEY106_1,
   "KEY107_1": KEY107_1,
   "KEY108_1": KEY108_1,
   "KEY108_2": KEY108_2,
   "KEY109_1": KEY109_1,
   "KEY110_1": KEY110_1,
   "KEY111_1": KEY111_1,
   "KEY112_1": KEY112_1,
   "KEY201_1": KEY201_1,
   "KEY202_1": KEY202_1,
   "KEY203_1": KEY203_1,
   "KEY204_1": KEY204_1,
   "KEY205_1": KEY205_1,
   "KEY206_1": KEY206_1,
   "KEY207_1": KEY207_1,
   "KEY208_1": KEY208_1,
   "KEY209_1": KEY209_1,
   "KEY210_1": KEY210_1,
   "KEY211_1": KEY211_1,
   "KEY212_1": KEY212_1,
   "KEY213_1": KEY213_1,
   "KEY214_1": KEY214_1,
   "KEY215_1": KEY215_1,
   "KEY216_1": KEY216_1,
   "KEY301_1": KEY301_1,
   "KEY302_1": KEY302_1,
   "KEY303_1": KEY303_1,
   "KEY304_1": KEY304_1,
   "KEY305_1": KEY305_1,
   "KEY306_1": KEY306_1,
   "KEY307_1": KEY307_1,
   "KEY308_1": KEY308_1,
   "KEY309_1": KEY309_1,
   "KEY310_1": KEY310_1,
   "KEY311_1": KEY311_1,
   "KEY312_1": KEY312_1,
   "KEY313_1": KEY313_1,
   "KEY314_1": KEY314_1,
   "KEY315_1": KEY315_1,
   "KEY316_1": KEY316_1,
        }
ratescale = []
ratescale.append({"FAMILY SIZE": 1,
                  "2OW_RENT": "",
                  "2OW_LIMIT": "",
                  "3OW_RENT": 85,
                  "3OW_LIMIT": 360,
                  "4ODSP_RENT": 109,
                  "4ODSP_LIMIT": 440})
ratescale.append({"FAMILY SIZE": 2,
                  "2OW_RENT": 191,
                  "2OW_LIMIT": 791,
                  "3OW_RENT": 175,
                  "3OW_LIMIT": 737,
                  "4ODSP_RENT": 199,
                  "4ODSP_LIMIT": 817})
ratescale.append({"FAMILY SIZE": 3,
                  "2OW_RENT": 226,
                  "2OW_LIMIT": 907,
                  "3OW_RENT": 212,
                  "3OW_LIMIT": 861,
                  "4ODSP_RENT": 236,
                  "4ODSP_LIMIT": 941})
ratescale.append({"FAMILY SIZE": 4,
                  "2OW_RENT": 296,
                  "2OW_LIMIT": 1051,
                  "3OW_RENT": 254,
                  "3OW_LIMIT": 1001,
                  "4ODSP_RENT": 279,
                  "4ODSP_LIMIT": 1081})
ratescale.append({"FAMILY SIZE": 5,
                  "2OW_RENT": 311,
                  "2OW_LIMIT": 111,
                  "3OW_RENT": 296,
                  "3OW_LIMIT": 1141,
                  "4ODSP_RENT": 321,
                  "4ODSP_LIMIT": 1224})
ratescale.append({"FAMILY SIZE": 6,
                  "2OW_RENT": 353,
                  "2OW_LIMIT": 1331,
                  "3OW_RENT": 339,
                  "3OW_LIMIT": 1284,
                  "4ODSP_RENT": 363,
                  "4ODSP_LIMIT": 1364})
ratescale.append({"FAMILY SIZE": 7,
                  "2OW_RENT": 396,
                  "2OW_LIMIT": 1474,
                  "3OW_RENT":  381,
                  "3OW_LIMIT": 1424,
                  "4ODSP_RENT": 405,
                  "4ODSP_LIMIT": 1504})
ratescale.append({"FAMILY SIZE": 8,
                  "2OW_RENT": 438,
                  "2OW_LIMIT": 1614,
                  "3OW_RENT": 423,
                  "3OW_LIMIT": 1564,
                  "4ODSP_RENT": 448,
                  "4ODSP_LIMIT": 1647})
ratescale.append({"FAMILY SIZE": 9,
                  "2OW_RENT": 480,
                  "2OW_LIMIT": 1754,
                  "3OW_RENT": 466,
                  "3OW_LIMIT": 1707,
                  "4ODSP_RENT": 490,
                  "4ODSP_LIMIT": 1787})
ratescale.append({"FAMILY SIZE": 10,
                  "2OW_RENT": 523,
                  "2OW_LIMIT": 1897,
                  "3OW_RENT": 508,
                  "3OW_LIMIT": 1897,
                  "4ODSP_RENT": 532,
                  "4ODSP_LIMIT": 1847})
ratescale.append({"FAMILY SIZE": 11,
                  "2OW_RENT": 565,
                  "2OW_LIMIT": 2037,
                  "3OW_RENT": 550,
                  "3OW_LIMIT": 1847,
                  "4ODSP_RENT": 575,
                  "4ODSP_LIMIT": 1987})
ratescale.append({"FAMILY SIZE": 12,
                  "2OW_RENT": 607,
                  "2OW_LIMIT": 2177,
                  "3OW_RENT": 593,
                  "3OW_LIMIT": 2131,
                  "4ODSP_RENT": 617,
                  "4ODSP_LIMIT": 2211})

byunitlist = [1, 2, 3, 4, 5, 6, 7,  8, 9, 10, 11, 12, 13, 14, 15, 16,  17, 18, 19, 20, 21, 22, 23, 24, 25,  26, 27, 28, 29, 30, 31, 32, 33, 34,  35, 36, 37, 38, 39, 40, 41, 42, 43,   44, 45, 46, 101, 102, 103, 104, 105,  106, 107, 106, 109, 110, 111, 112,  201, 202, 203, 204, 207, 206, 207,  208, 209, 210, 211, 212, 213, 214,  215, 216, 301, 302, 303, 304, 307,  306, 307, 306, 309, 310, 311, 312,  313, 314, 315]

bynamelist = []

SCData = {
        "members     ": members,
        "ratescale     ": ratescale,
        "byunitlist     ": byunitlist,
        "bynamelist     ": bynamelist
        }
print(SCData)
picklesave = open("SCData.pickle     ",      "wb")
pickle.dump(SCData, picklesave)
picklesave.close()
